language: go

go:
    - 1.8

before_install:
    - curl -L https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz -o glide.tar.gz
    - tar xfv glide.tar.gz

# override default install
install: true

script:
    - ./linux-amd64/glide install --strip-vendor
    - go install ./vendor/github.com/karalabe/hid/...
    - go install ./vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/...
    - go test -v ./sublimate/... ./cmd/...
