language: go

go:
    - tip

before_install:
    - sudo add-apt-repository ppa:masterminds/glide -y
    - sudo apt-get update -q
    - sudo apt-get install glide -y

script:
    - glide install
    - go test -v ./sublimate/... ./cmd/...
